# Generated by Django 4.2.17 on 2024-12-28 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fortunaisk', '0002_setup_periodic_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], help_text='The type of action performed.', max_length=10, verbose_name='Action Type')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the action was performed.', verbose_name='Timestamp')),
                ('model', models.CharField(help_text='The model on which the action was performed.', max_length=100, verbose_name='Model')),
                ('object_id', models.PositiveIntegerField(help_text='The ID of the object on which the action was performed.', verbose_name='Object ID')),
                ('changes', models.JSONField(blank=True, help_text='A JSON object detailing the changes made.', null=True, verbose_name='Changes')),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed the action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
